newsfeed/urls.py
from django.conf.urls import patterns, url, include
# from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.urlpatterns import format_suffix_patterns
from newsfeed import views


urlpatterns = patterns('',
	
    url(r'^$', views.index, name='index'),
    url(r'^$', views.base, name='base'),
    url(r'^documentation$', views.documentation, name='documentation'),
    url(r'^auth$', views.auth, name='auth'),
    url(r'^login$', views.login, name='login'),
    url(r'^signup$', views.signup, name='signup'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^new_post$', views.new_post, name='new_post'),
    url(r'^offline$', views.offline, name='offline'),
    url(r'^create_post$', views.create_post, name='create_post'),
    url(r'^login_user$', views.login_user, name='login_user'),
    url(r'^create_user$', views.create_user, name='create_user'),
    url(r'^post/(?P<post_id>\d+)/$', views.single_post, name='single_post'),
    url(r'^post/(?P<post_id>\d+)/$', views.single_tag, name='single_tag'),
    url(r'^tag/(?P<tag_id>\d+)/$', views.single_tag, name='single_tag'),
    url(r'^tags_of_a_post/(?P<post_id>\d+)/$', views.tags_of_a_post, name='tags_of_a_post'),
    url(r'^search$', views.search, name='search'),
    url(r'^suggested$', views.suggested, name='suggested'),
    url(r'^post_tag$', views.post_tag, name='post_tag'),
    url(r'^users/$', views.UserList.as_view()),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserDetail.as_view()),
    url(r'^posts/$', views.PostList.as_view()),
    url(r'^posts/(?P<pk>[0-9]+)/$', views.PostDetail.as_view()),
    url(r'^tags/$', views.TagList.as_view()),
    url(r'^tags/(?P<pk>[0-9]+)/$', views.TagDetail.as_view()),
)

urlpatterns = format_suffix_patterns(urlpatterns)

#urls for login not sure if needed

#urlpatterns += [
#    url(r'^api-auth/', include('rest_framework.urls',
#                               namespace='rest_framework')),
#]

pintergram/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponseRedirect

#http://www.kelvinwong.ca/tag/media_root/ ^
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    url(r'^$', lambda r: HttpResponseRedirect('newsfeed/login')),
    url(r'^newsfeed/', include('newsfeed.urls', namespace="newsfeed")),
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsfeed/models.py
from time import time
from datetime import datetime
from django.db import models
# from pygments.lexers import get_all_lexers
# from pygments.styles import get_all_styles

#class User(models.Model):
#    username = models.CharField(max_length=30)
#    first_name = models.CharField(max_length=30)
#    last_name = models.CharField(max_length=50)
#    password = models.CharField(max_length=30)
#    email = models.EmailField()
    #outdated but cool for MVP
#    avatar_path = models.FilePathField("/images/avatars", blank=True)
#    def __str__(self):              # __unicode__ on Python 2
#        return self.username
    

#http://code.techandstartup.com/django/images/#images-templates
def generate_filename(instance, filename):
    ext = filename.split('.')[-1]
    return 'images/' + str(int(time())) + '.' + ext



class Post(models.Model):
    owner = models.ForeignKey('auth.User', related_name='posts')
    post_title = models.CharField(max_length=100)
    post_text = models.TextField(max_length=5000)

    image_path = models.ImageField(upload_to=generate_filename, blank=True, null=True)

    timestamp = models.DateTimeField(default=datetime.now)

    def __str__(self):              # __unicode__ on Python 2
        return self.post_title

class Tag(models.Model):
    post_id = models.ForeignKey(Post, related_name="tags")
    tag = models.CharField(max_length=100)
    def __str__(self):              # __unicode__ on Python 2
        return self.tag

class Follower(models.Model):
    follower_id = models.ForeignKey('auth.User', related_name='follower_set')
    followee_id = models.ForeignKey('auth.User', related_name='followee_set')
    def __str__(self):              # __unicode__ on Python 2
        return self.followee_id

class Preferences(models.Model):
    owner = models.ForeignKey('auth.User')
    tag = models.CharField(max_length=100)
    num = models.IntegerField()
    def __str__(self):
        return self.tag

class Upvote(models.Model):
    post_id = models.ForeignKey(Post)
    original_poster = models.ForeignKey('auth.User', related_name='op_set')
    voter_set       = models.ForeignKey('auth.User', related_name='voter_set')
    def __str__(self):              # __unicode__ on Python 2
        return "upvote"

newsfeed/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core import serializers
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.datastructures import MultiValueDictKeyError
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_exempt

from rest_framework import viewsets

# from django.views.decorators.csrf import csrf_exempt
# from rest_framework.renderers import JSONRenderer
# from rest_framework.parsers import JSONParser


from newsfeed.serializers import UserSerializer, UserSerializerPut, PostSerializer, PostSerializerPut, TagSerializer, TagSerializerPut
from newsfeed.models import Post, Tag, Follower, Upvote, Preferences

from rest_framework import status
from rest_framework.decorators import api_view
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.response import Response

from django.contrib.auth.models import User

from newsfeed.serializers import UserSerializer
from rest_framework import generics

# for auth

from rest_framework import permissions
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.hashers import make_password

# @cache_page(60 * 1)
def index(request):
    latest_post_list = Post.objects.order_by('-timestamp')
    tag_list = []
    for post in latest_post_list:
        tag_group = Tag.objects.filter(post_id=post)
        tag_list.append(tag_group)
    zipped_lists = zip(latest_post_list, tag_list)
    context = {'zipped_lists': zipped_lists, 'latest_post_list': latest_post_list, 'self_un': request.user}
    return render(request, 'newsfeed/index.html', context)

def new_post(request):
    return render(request, 'newsfeed/new_post.html')

def base(request):
    return render(request, 'newsfeed/base.html')


def offline(request):
    return render(request, 'newsfeed/offline.html')

def login(request):

    return render(request, 'newsfeed/login.html')

def signup(request):
    return render(request, 'newsfeed/signup.html')


    if request.method == 'GET':
        return render(request, 'newsfeed/login.html')

def login_user(request):
    if not request.POST['username']:
        return HttpResponseRedirect('/newsfeed/login')
    elif not request.POST['password']:
        return HttpResponseRedirect('/newsfeed/login')
    else:
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                return HttpResponseRedirect('/newsfeed')
            else:
                return HttpResponseRedirect('/newsfeed/login')
        else:
            return HttpResponseRedirect('/newsfeed/login')

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect('/newsfeed/login')

def create_user(request):
    if request.method == 'GET':
        return render(request, 'newsfeed/create_user.html')
    elif request.method == 'POST':
        new_user = User(username=request.POST['username'],
                        first_name=request.POST['first_name'],
                        last_name=request.POST['last_name'],
                        email=request.POST['email'],
                        password=make_password(request.POST['password']),
                        is_staff=False,
                        is_active=True,
                        is_superuser=False)
        new_user.save()
        return HttpResponseRedirect('/newsfeed/login')


def create_post(request):
    try:
        image = request.POST['post-image']
    except MultiValueDictKeyError:
        image = request.FILES['post-image']
    except MultiValueDictKeyError:  
        image = None

    if not request.POST['post_title']:
        return HttpResponseRedirect('/newsfeed')
    elif not request.POST['post_text'] and not image:
        return HttpResponseRedirect('/newsfeed')
    else:
        new_post = Post(post_text=request.POST['post_text'], 
                        post_title=request.POST['post_title'], 
                        timestamp=timezone.now(), 
                        owner=request.user)
        if image:
            new_post.image_path = request.FILES['post-image']
        new_post.save()
        tag_string = request.POST['tags']
        if tag_string:
            tag_list = [x.strip() for x in tag_string.split(',')]
            # tag_list = tag_string.split(',')
            for x in tag_list:
                new_tag = Tag(tag=x, post_id=new_post)
                new_tag.save()
                old_pref = Preferences.objects.filter(owner=request.user).filter(tag=x)
                if old_pref:
                    old_pref[0].num = old_pref[0].num + 1
                    old_pref[0].save()
                else:
                    new_pref = Preferences(owner=request.user, tag=x, num=1)
                    new_pref.save()
        return HttpResponseRedirect('/newsfeed')
        # return HttpResponse('')

# @cache_page(60 * 10)
def single_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    tags = Tag.objects.filter(post_id=post)
    return render(request, 'newsfeed/single_post.html', {'post': post, 'tags': tags, 'self_un': request.user})

def post_tag(request):
    if request.method == 'POST':
        new_post = Post.objects.order_by('-timestamp')[0]
        try:
            tag_string = request.POST['tags']
        except MultiValueDictKeyError:
            tag_string = None
        if tag_string:
            tag_list = [x.strip() for x in tag_string.split(',')]
            # tag_list = tag_string.split(',')
            for x in tag_list:
                new_tag = Tag(tag=x, post_id=new_post)
                new_tag.save()
                old_pref = Preferences.objects.filter(owner=request.user).get(tag=x)
                if old_pref:
                    old_pref.num = old_pref.num + 1
                    old_pref.save()
                else:
                    new_pref = Preferences(owner=request.user, tag=x, num=1)
                    new_pref.save()
        return HttpResponseRedirect('/newsfeed')

def single_tag(request, tag_id):
    tag_name = Tag.objects.get(pk=tag_id)
    used_tag_list = Tag.objects.filter(tag=tag_name.tag)
    tagged_post_list = []
    tag_list = []
    for tag in used_tag_list:
        tagged_post_list.insert(0, tag.post_id)
    for post in tagged_post_list:
        tag_group = Tag.objects.filter(post_id=post)
        tag_list.append(tag_group)
    zipped_lists = zip(tagged_post_list, tag_list)
    context = {'zipped_lists': zipped_lists, 'tagged_post_list': tagged_post_list, 'self_un': request.user}
    return render(request, 'newsfeed/tag.html', context)

def tags_of_a_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    tag_group = Tag.objects.filter(post_id=post)
    JSONSerializer = serializers.get_serializer("json")
    json_serializer = JSONSerializer()
    json_serializer.serialize(tag_group)
    tags = json_serializer.getvalue()
    # tags = serializers.serializer("json", tag_group)
    return HttpResponse(tags, content_type='application/json')

def suggested(request):
    top_tags = Preferences.objects.filter(owner=request.user).order_by('-num')
    post_groups = []

    i = 0
    for top_tag in top_tags:
        if (i < 5):
            used_tags = Tag.objects.filter(tag=top_tag)
            used_text = Post.objects.filter(post_text__contains=top_tag)
            used_title = Post.objects.filter(post_title__contains=top_tag)
            tagged_post_list = []
            tag_list = []
            for tag in used_tags:
                tagged_post_list.insert(0, tag.post_id)
            for post in tagged_post_list:
                tag_group = Tag.objects.filter(post_id=post)
                tag_list.insert(0, tag_group)

            for post in used_text:
                tagged_post_list.insert(0, post)
                tag_group = Tag.objects.filter(post_id=post)
                tag_list.insert(0, tag_group)

            for post in used_title:
                tagged_post_list.insert(0, post)
                tag_group = Tag.objects.filter(post_id=post)
                tag_list.insert(0, tag_group)

            zipped_post = zip(tagged_post_list, tag_list)
            post_groups.append(zipped_post)
            i = i + 1
    zipped_groups = zip(post_groups, top_tags)
    context = {'zipped_groups': zipped_groups, 'self_un': request.user}
    return render(request, 'newsfeed/suggested.html', context)
    # JSONSerializer = serializers.get_serializer("json")
    # json_serializer = JSONSerializer()
    # json_serializer.serialize(post_groups)
    # json = json_serializer.getvalue()
    # return HttpResponse(top_tags, content_type='text')

def search(request):
    tag_name = request.POST['search_input']

    used_tag_list = Tag.objects.filter(tag=tag_name)
    used_posttext_list = Post.objects.filter(post_text__contains=tag_name)
    used_posttitle_list = Post.objects.filter(post_title__contains=tag_name)

    tagged_post_list = []

    tag_tag_list = []
    text_tag_list = []
    title_tag_list = []

    for tag in used_tag_list:
        tagged_post_list.insert(0, tag.post_id)
    for post in tagged_post_list:
        tag_group = Tag.objects.filter(post_id=post)
        tag_tag_list.append(tag_group)

    for post in used_posttext_list:
        tag_group = Tag.objects.filter(post_id=post)
        text_tag_list.append(tag_group)

    for post in used_posttitle_list:
        tag_group = Tag.objects.filter(post_id=post)
        title_tag_list.append(tag_group)

    zipped_tags = zip(tagged_post_list, tag_tag_list)
    zipped_text = zip(used_posttext_list, text_tag_list)
    zipped_title = zip(used_posttitle_list, title_tag_list)

newsfeed/templates/newsfeed/base.html
{% load staticfiles %}



<style type="text/css">
	header {
		background-repeat:no-repeat;
    	background-size:cover;
    	height: 60px;
    	color:#fff;
    	background-color: #7bd9c6;
	}
	.create-icon {
		float: right;

	}
	.create-icon img, p {
		height: 40px;
		
	}
.create-icon img {
		opacity: .8;
		margin: 10px !important;
		float: left;
	}

#create-icon-img:hover {
		opacity: 1;
	}

	#create-icon-txt {
		opacity: 0;
		width: 0;
		overflow-x:hidden;
		display: inline;
		margin:0;
		margin-top: 10px;
		margin-bottom: 10px;
		height: 40px;
/*		width: 40px;
		height: 40px;*/
		float: left;
		line-height: 40px;
		font-size: 20px;
		white-space: nowrap;

	    /*opacity: 0;*/
	/*    transition: width 1s ease-in-out;
	    -moz-transition: width 1s ease-in-out;
	    -webkit-transition: width 1s ease-in-out;
	    transition: opacity 1s ease-in-out;
	    -moz-transition: opacity 1s ease-in-out;
	    -webkit-transition: opacity 1s ease-in-out;*/
	 	transition: all .5s ease-in-out;
	    -moz-transition: all .5s ease-in-out;
	    -webkit-transition: all .5s ease-in-out;
	 	
	}

	.create-icon:hover  #create-icon-txt {
		width: 175px;
		opacity: 1.0;
	    transition: all .5s ease-in-out;
	    -moz-transition: all .5s ease-in-out;
	    -webkit-transition: all .5s ease-in-out;
	    
	}
	.create-icon:hover #create-icon-img {
		opacity: 1;
	}

	#logout-button:hover  #create-icon-txt {
		width: 90px;
		opacity: 1.0;
	    transition: all .5s ease-in-out;
	    -moz-transition: all .5s ease-in-out;
	    -webkit-transition: all .5s ease-in-out;
	    
	}
	#logout-button:hover #create-icon-img {
		opacity: 1;
	}
	#logout-button {
		margin-right: -10px;
	}



#modal {
  background: black;

  position: fixed;
  width: 50%;
  top: 50%;
  left: 50%;
  margin: -25% 0 0 -25%;

  /* Embiggen */
  transform: scale(1.5); /* prefix me */

  /* Hidden */
  opacity: 0;
  pointer-events: none;
}

.createIsOpen #main-content {

  /* Blur and de-color */
  -webkit-filter: blur(5px) grayscale(50%);

  /* Recede */
  /*-webkit-transform: scale(0.9);*/

}

.createIsOpen #modal {
  
  /* Regular size and visible */
  transform: scale(1); /* prefix me */
  opacity: 1;

  /* Clickable */
  pointer-events: auto;

}

#main-content, #modal {
  
  transition: all 0.4s ease; /* prefix me */

}
.margin-60px-sides {
	margin-left:60px;
	margin-right:60px;
	margin-top: 30px;
	margin-bottom: 30px;
}
	
.curr-user-avatar {
	width: 100%;
	border-radius: 50%
}
.curr-user-avatar img {
	border-radius: 50%;
}

.width-100 {
	width: 100%;
}
.text-align-center {
	text-align: center;
}

.curr-user-username {
	border-bottom: solid 2px #fff;
}


.search-form{
/*	width:500px;*/
	/*margin:0 auto;*/
}
.search { 
	padding:6px 15px 6px 50px;
	margin:10px; 
	repeat 8px 6px; 
	border-radius:15px; 
	-moz-border-radius:15px; 
	-webkit-border-radius:15px; 
	margin-right: 0;
	height: 40px;
	background: rgba(255, 255, 255, 0.6);
	background-image: url("{% static 'newsfeed/img/search-icon.png' %}") no-repeat 8px 6px;
	border: none;
}
.lighter-search {
	/*width:95%;*/
	/*height:50px;*/
	display: inline-block;
	float: right;
	background: url("{% static 'newsfeed/img/search-icon.png' %}") no-repeat 8px 6px;
	
	color:#797979;
}

.tags a {
	color: #3b8473;
}

.search-icon {
	height: 40px;
	margin-right: -60px;
}

h2.post {
  background:none !important;
}


.post-image-index {
	width: 100%;
	height: auto;


}

#suggested-button {
	margin-right: -10px;
	color: #fff;
}
</style>



<!DOCTYPE html>
<html lang="en" manifest="manifest.appcache">
	<head>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="Dashboard">
		<meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
		<title>pintergram</title>
		<link rel="stylesheet" type="text/css" href="{% static 'newsfeed/css/all-style.css' %}" /> <!-- dont forget to put min back -->
		<link rel="shortcut icon" href="{% static 'newsfeed/img/favicon.ico' %}">
	</head>

	<body>


	{% block login-content %}

	<section id="container" class="sidebar-closed">
	  <!-- **********************************************************************************************************************************************************
	  TOP BAR CONTENT & NOTIFICATIONS
	  *********************************************************************************************************************************************************** -->
	  <!--header start-->
		<header class="header" >
			<!-- <div class="header transparent-header"></div> -->
		
			<!--logo start-->
			<a href="{% url 'newsfeed:index' %}" class="logo">
			  <img class="nav-logo"src="{% static 'newsfeed/img/full-logo-white.png' %}">
			</a>
			<!--logo end-->
			<!-- <a href="{% url 'newsfeed:new_post' %}"> -->
			<!-- <div class="create-button monofur-font" id="create-button" onclick="open_create()">
			  create something
			</div> -->
			<!-- </a> -->

		
			<!-- <div class="create-icon" id="create-button" onclick="open_create()"> -->

			<div class="create-icon" id="create-button">
				<img class="nav-logo" id="create-icon-img" src="{% static 'newsfeed/img/create-icon.png' %}">
				<p class="monofur-font" id="create-icon-txt">create somthing</p>
				
				
			</div>
			<a href="{% url 'newsfeed:suggested' %}" style="text-decoration:none;">
			<div class="create-icon" id="suggested-button">
				<img class="nav-logo" id="create-icon-img" src="{% static 'newsfeed/img/suggested-icon.png' %}">
				<p class="monofur-font" id="create-icon-txt">suggested for you</p>
				
				
			</div>
			</a>
			
			<div class="create-icon" id="logout-button">
				<img class="nav-logo" id="create-icon-img" src="{% static 'newsfeed/img/logout-icon.png' %}">
				<p class="monofur-font" id="create-icon-txt">log out</p>
				
				
			</div>
			<div class="lighter-search">

				<form class="search-form" id="search_bar" method="post" action="{% url 'newsfeed:search' %}">{% csrf_token %}
					<span>
						<img class="search-icon" src="{% static 'newsfeed/img/search-icon.png' %}">
						<input type="text" class="search rounded" id="search_input" name="search_input" placeholder="Search..."></span>

				</form>
			</div>

			

	

			

<!-- 
			<div class="onoffswitch monofur-font" id="view-switch">
				<input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked>
				<label class="onoffswitch-label" for="myonoffswitch">
					<span class="onoffswitch-inner">
					  
					</span>
					<span class="onoffswitch-switch"></span>
				</label>
			</div> -->

		</header>
	  <!--header end-->
	  
	  <!-- **********************************************************************************************************************************************************
	  MAIN SIDEBAR MENU
	  *********************************************************************************************************************************************************** -->


	  
	  <!--main content start-->
	  	<section id="main-content">
		  	<section class="wrapper site-min-height">
				<!-- <div class="row mt"> -->

					<div class="col-lg-10" id="main-content-stream">
				  
						{% block new-post %}{% endblock %}
						{% block signup %}{% endblock %}
						{% block newsfeed-content %}{% endblock %}
						{% block offline %}{% endblock %}
					</div> <!-- LAST DIV-->
					<div class="col-lg-2">
						<div class="new-sidebar monofur-font">
							<div class="margin-60px-sides">
								<div class="curr-user-avatar">
									<img class="width-100" src="{% static 'newsfeed/img/ui-danro.jpg' %}">
								</div>
								<div class="curr-user-fullname text-align-center">
									<h3 id="fullname"></h3>
								</div>
								<div class="curr-user-username text-align-center">
									<h4 id="current_user"></h4>
								</div>
								<br>
								<div class="sidebar-stats">
									<h4 class="text-align-center monofur-font">Upvotes | 999</h4>
								</div>
								<div class="sidebar-stats">
									<h4 class="text-align-center monofur-font">Followers | 47</h4>
								</div>
								<div class="sidebar-stats">
									<h4 class="text-align-center monofur-font">Following | 82</h4>
								</div>

							</div>


					
						</div>
					</div>
				<!-- </div> -->
			</section><!--/wrapper -->
		</section><!-- /MAIN CONTENT -->

	  <!--main content end-->
	  <!--footer start-->
		<footer class="site-footer">
		  	<div class="text-center" id="site_footer">
			  2014 - Team 14 - 
			  <a href="{% url 'newsfeed:documentation' %}">Documentation</a>
			  	<a href="blank.html#" class="go-top">
				  	<i class="fa fa-angle-up"></i>
			  	</a>
		  	</div>
		</footer>
	  <!--footer end-->
	</section>

	<div id="modal">
	    <!-- modal box content -->
				<div class="floating-mod monofur-font">
					<div class="floating-mod-title"> lets get creative</div>
				
					{% block new-post-mod %}{% endblock %}
				</div>
	</div>

	<!-- js placed at the end of the document so the pages load faster -->

		<script src="{% static 'newsfeed/js/all-js.js' %}" type="text/javascript"></script> 
<script type="text/javascript">
$("#create-button").on("click", function() {

  // State changes
  $("body").toggleClass("createIsOpen");

});

$("#new-post-button").on("click", function() {

  // State changes
	$("body").toggleClass("createIsOpen");



});

$("#main-content-stream").on("click", function() {

  // State changes
  if ($("body").hasClass("createIsOpen")) {
  	$("body").toggleClass("createIsOpen");
  }
	



});


$("#logout-button").on("click", function() {
	location.href = "{% url 'newsfeed:logout' %}";
  	
});

$("#search_input").keypress(function (e) {
  if (e.which == 13) {
  	// console.log($('#search_bar').serialize());
  	// alert("working");
    $("#search_bar").submit();

    // $.ajax({
    //             url:"{% url 'newsfeed:search' %}",
    //             type:'post',
    //             enctype: "multipart/form-data",
    //             data:$('#search_bar').serialize(),
    //             success:function(){
    //                 // alert("worked");
    //             }
    //  });

    // console.log($('#search_input').val());
    // location.href = "search/" + $('#search_input').val();
    // e.preventDefault();
  }
});

$("#current_user").innerText = "{{ self_un.username }}";
document.getElementById("fullname").innerText = "{{ self_un.first_name }} {{ self_un.last_name }}";
document.getElementById("current_user").innerText = "{{ self_un.username }}";

</script>

{% endblock %}
	</body>

</html>

newsfeed/templates/newsfeed/create_post.html
<h1>post something</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="/newsfeed/" method="post">
{% csrf_token %}

    <input type="text" name="post_title" id="post_title"/>
    <input type="text" name="post_text" id="post_text"/>


<input type="submit" value="Vote" />
</form>

newsfeed/templates/newsfeed/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% block login-content %}

<style type="text/css">
	header {
		display: none !important;
	}
	.main-content {
		/*background-image: url(/static/newsfeed/img/navbar2.png) !important;*/
		display: none !important;
	}

footer {
		display: none !important;
	}


</style>


<div class="login-column monofur-font">
	
	<div class="login-window ">
	<a class="login-button bg-light-mint mint-button login-input" href="create_user" id="create-user-at-login">create user</a>
		<!-- <h3 class="login-title">let's get creative</h3> -->
		<a href="{% url 'newsfeed:index' %}" class="login-logo">
			<img class="nav-logo"src="{% static 'newsfeed/img/full-logo-mint.png' %}">
		</a>

		<form action="login_user" method="post" enctype="multipart/form-data" id="login-form">
			{% csrf_token %}
			<input class="login-input" type="text" name="username" placeholder="username">
			<br>
			<input class="login-input" type="password" name="password" placeholder="password">
			<button class="login-button bg-light-mint mint-button login-input" type="submit" form="login-form" value="login">log in</button>
		</form>
		
	</div>
	

	
	
</div>


<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript">
	$(function() {
	$('.fadein img:gt(0)').hide();

	setInterval(function () {
	    $('.fadein :first-child').fadeOut()
	                             .next('img')
	                             .fadeIn()
	                             .end()
	                             .appendTo('.fadein');
	}, 4000); // 4 seconds
	});
</script>




{% endblock %}

newsfeed/templates/newsfeed/newsfeed.html
{% if latest_post_list %}
    <ul>
    {% for post in latest_post_list %}
        <li>{{ post.post_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No posts are available.</p>
{% endif %}


<h1>post something</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="/newsfeed/" method="post">
{% csrf_token %}

    <input type="text" name="post_title" id="post_title"/>
    <input type="text" name="post_text" id="post_text"/>


<input type="submit" value="Vote" />
</form>

newsfeed/templates/newsfeed/offline.html
{% extends "base.html" %}
{% load staticfiles %}

{% block offline %}




<div class="post pn offline-warning monofur-font">
	<div class=" offline-warning-header">
			oh no!	
	</div>
	<div class=>
		
	</div>
	<p>The page you were looking for is offline!</p>
	<p>Here's a muffin to cheer you up</p>
	<img src="{% static 'newsfeed/img/muffin.png' %}">

</div>




{% endblock %}